spring:
  security:
    oauth2:
      client:
        registration:
          idsvr:
            client-id: jwe-client
            client-secret: Password1
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/curity"
            scope: openid, profile
        provider:
          idsvr:
            issuer-uri: http://login.example.com:8443/dev/oauth/anonymous